engines:
  fixme:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        - javascript
    exclude_fingerprints:
      - 91ca2a54221a0969b3be95ab62b683ec

  eslint:
    enabled: true

ratings:
  paths:
    - lib/**
    - test/**
